_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 53
            "2":
                - 1
                - 53
            "3":
                - 2
                - 13
                - 16
                - 55
            "4": 3.11.12
            "5": 0.20.1
            "8":
                - 1
            "12": 0.20.1
            "13": linux-x86_64
Discpription:
    value: Implementing simple CNN model that upsacale using one transposed layer. Last just run for 5 epoachs, now 10 epochs.
batch_size:
    value: 1
dataset:
    value: SSU_NMC
dataset_size:
    value: 3843
dataset_split:
    value:
        test: 768
        train: 2305
        val: 770
device:
    value: cuda
epochs:
    value: 10
learning_rate:
    value: 0.001
loss_function:
    value: MSE loss
model:
    value: CNN_vanilla
model_parameters:
    value: 2283777
optimizer:
    value: Adam
positional_encoding_dim:
    value: 10
