_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 5
                - 13
                - 14
                - 15
                - 16
                - 55
                - 62
            "4": 3.11.12
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 16
config_file_name:
    value: config_50_12082025_1100.yaml
data_description:
    value: Generated SDF of 32, 64, 128, 256 data using NMC logic
data_name:
    value: V1_Manual_Extracted_NMC_Data_large
data_size:
    value: 5351
dataset_grids:
    value:
        - 32
        - 128
dataset_split:
    value:
        test: 0.2
        train: 0.6
        val: 0.2
discription:
    value: 'Change: epochs increased to 300'
epochs:
    value: 300
eval_data_name:
    value: ABC
eval_discription:
    value: 32 -> 128
eval_normalize:
    value: NDC Normalization
eval_run:
    value: true
input_size:
    value: 33
learning_rate:
    value: 0.001
loss_function:
    value: mse_loss
mask_threshold:
    value: 65
model_name:
    value: 50_rerun_49_with_300_epochs
model_parameters:
    value: null
optimizer:
    value: Adam
unique_random_direction:
    value: true
upsample_factor:
    value: 4
