_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
                - 55
            "4": 3.11.12
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 8
config_file_name:
    value: config_37_17072025_1300.yaml
crop_size:
    value: 16
crop_threshold:
    value: 400
data_description:
    value: Generated SDF of 32, 64, 128 data using NMC logic
data_name:
    value: V1_Manual_Extracted_NMC_Data
data_size:
    value: 5351
dataset_split:
    value:
        test: 0.2
        train: 0.6
        val: 0.2
discription:
    value: 'Chnage from last time: cnn with residual and trilinear. for 20 epoch. back to l1 loss.'
epochs:
    value: 20
eval_data_name:
    value: ABC
eval_normalize:
    value: NDC Normalization
eval_run:
    value: true
is_crop:
    value:
        test: false
        train: true
        val: false
learning_rate:
    value: 0.001
loss_function:
    value: l1_loss
loss_weights:
    value:
        - 0.25
        - 0.25
        - 0.5
mask_threshold:
    value: 33
model_name:
    value: 37_residual_CNN_Upsampler_Manual_NMC_data_l1
model_parameters:
    value: 150081
optimizer:
    value: Adam
positional_encoding:
    value: 10
upsampling_level:
    value: 2
